### ISSUE TITLE
Complete Part 1 Introduction to React

### ISSUE THREAD

**Issue by deepakgsrn** [deepakgsrn/full-stack-open#2]
in the course introduction to react the aim is to get introduced to React, brush up javascript, understanding react component state & event handlers, a more complex state & debugging react apps

**Comment by deepakgsrn** [comment]
**Sections in Part 1 - Introduction to React** | 10:40 pm Thursday, 14 October 2021 (IST)

Learning Outcome : To get familiarize with React Library & some features are JS that is important to understand React

- [x] Introduction to React
- [x] JavaScript
- [x] component State, Event Handlers
- [x] a more complex state, debugging react apps

**Comment by deepakgsrn** [comment]
**Introduction to React** | 10:40 pm Thursday, 14 October 2021 (IST)

React Library - Core Concepts of React - Component - JSX - props

Take Away's : 
- Core philosophy of react is composing applications from many specialized reusable components
- React application can be created with the tool called _create-react-app_ with `npm` & `node` installed
- The file index.js marks the entry point of the react application (assumption)
- Layout of the React Component is usually written with JSX which will be compiled to JS with the help of babel
- Unlike HTML, in JSX tags must be closed (eg `<br>` vs `<br  />`)
- Import at the top of the file, export at the bottom
- React component name must be always **capitilized** [eg. _Footer_ ✔️ : vs _footer_ ❌  ]
- Content of the react component usually need to contain **one root element** (in addition to this array of elements or using fragments is also an option but it is not advisable)
- Properties `props` are used to pass data from parent component to child component, there can be any number of props for a component
- When JavaScript expression is used, it must be enclosed in a curly braces `{ }`

#### 11:27 pm Thursday, 14 October 2021 (IST) &#11181; 
---

**Comment by deepakgsrn** [comment]
**JavaScript**

Learning Outcome : JavaScript Variables, Types, JS Functions, Behaviors, this keyword & other handlings

Take Away's :

- In JavaScript, there are 3 ways to create object. `let`, `const` & `var`, where `const` is actually a constant whose value cannot be changed. `let` and `const` are block scoped where `var` is available from the function it is declared.
- JavaScript Types are `Number, BigInt, String, Boolean, Symbol, Object [Array, RegEx, Function, Date ], null, undefined` & some buildin `Error` types
- JavaScript arrays can also be created as `const` still we can add or remove data from array this is because, the variable still points to the same array object but data inside the array is getting manipulated.
- React follows most of the characteristics of functional programming, one characteristics of functional programming is immutable datastructures. it is advisable to use method `concat` on array than `push`
- Another usefull feature of JavaScript is its `map` function, using `map` we can convert the values of an array in to some else (say html tags)
- Array Restructuring is another useful feature with which we can assign the values from an array using `const [first, second, ...rest] = [1, 2, 3, 4, 5];`
- functions defined with function keyword and Arrow functions differ substantially when it comes to how it behave when using `this`. In JavaScript the value of `this` is defined based on how the method is called. To preserve the value of original `this`, one of the way is using `bind` method.
- In JavaScript we can add functions to an existing object using Prototype, `String.prototype.reverseString = function() {//code//}`
- In JS, Class is added in ES6, but as we are using Hooks in React we may not use classes
- JS functions have access to additional parameter called `arguments` which is an array like object holding all the values passed to it.
- We can also use rest parameter syntax `...variable` to capture any number of values in arguments 
- In JS we can also create Anonymous functions which we can use to pass function as argument or as IIFE (Immediately Invoked Function Expression)
- Objects, Functions, Anonymous Functions, IIFE, Recursive Functions, Arrow Functions, Closures
- A Closure is a combination of a function and the scope object in which it was created.

**Comment by deepakgsrn** [comment]
**Component State, Event Handlers**

Learning Outcome : Handling States & Events in React

Take Away's 

- Function Components can have a function nested in to it called Component Helper function to handle specific logics separately which can access all the properties of the component without taking as argument
- Destructuring, values from an array/json can be directly destructured in to variables `const {name, gender}  = {name: 'Deepak', gender: 'male' }`
- Page Re-Rendering,
- Stateful Component, components can have state which could change during the lifecycle of components, in functional components state can be added with the help of state hooks `import React, { useState } from 'react'`, `const [ counter, setCounter ] = useState(0)`
- Event handlers can be added to react elements & it should be a function or a function reference
- for passing state to child components, it is recommended in react to lift the state up to their common closest ancestor when more than one components needs to reflect on same data
- calling a function which changes the state causes the component to re render

**Comment by deepakgsrn** [comment]
**a more complex state, debugging react apps**

Take Away's :

- a component's state and a piece of its state can be of any type. we can combine multiple properties in to a single object. ( single piece of state & event handler for the entire application state)
- we can use object spread `{...variable, x: 5}` syntax & specify only the properties that are changing to avoid mentioning unchanged properties
- We shouldn't update the state directly, It is forbidden in react to mutate state directly to avoid unexpected side effects
- Arrays can be created with `useState([])` & new values can be added to an array using `concat` method as it doesn't mutate the existing array. [`push` shouldn't be used as it mutate the state directly]
- Conditional Rendering can be performed while rendering the components. **useState shouldn't be used with any conditions as it relies on the order in which it is written**
- `state hook` is available from react version 16.8.0, in old versions the only way to have state is class components
- debugging react applications, keep the developer console open all the time 👀 , console.log can be used with comma separated values (avoid java like concatenation)/ `debugger` command can also be used to debug the application
- We can also add breakpoints directly in source tab without using debugger command & scope section is where values are visible
- Rules of Hooks , `useState` as well as `useEffect` must not be called inside of a loop, conditional expressions or any place that is not a function defining components
- Event Handler should be a function or a function reference & should not be a function call.
- Event handlers can be a function returns another functions
- Event handlers can be passed as an attributes to a child component from parent component
- Do not define components inside another components
- Work on Exercises 1.6 - 1.14 [Exercises 1.6 - ~1.11~ 1.14 Completed]

**Comment by deepakgsrn** [comment]
9.5 + 2.5 + 2 + 2 + 1 = 17h

**Comment by deepakgsrn** [comment]
9.5 + 2.5 + 2 + 2 + 1 = 17h
